# Generated by Django 5.1.4 on 2025-01-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Random quiz', max_length=250, unique=True, verbose_name='Quiz title'),
        ),
    ]
