# Generated by Django 5.1.4 on 2025-01-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='answer',
        ),
    ]
